FROM python:3.10-alpine
RUN mkdir -p /opt/cisco/wccai/byova-ai-simulator
RUN apk update

COPY . /opt/cisco/wccai/byova-ai-simulator
WORKDIR /opt/cisco/wccai/byova-ai-simulator
RUN apk add --no-cache py3-pip
RUN apk add --no-cache py3-pip ffmpeg flac

RUN python3 -m venv /opt/cisco/wccai/byova-ai-simulator/venv && \
    /opt/cisco/wccai/byova-ai-simulator/venv/bin/pip install --no-cache-dir -r /opt/cisco/wccai/byova-ai-simulator/requirements.txt

# Fetch proto schemas from GitHub API
RUN /opt/cisco/wccai/byova-ai-simulator/venv/bin/python /opt/cisco/wccai/byova-ai-simulator/fetch_proto_schema.py

WORKDIR /opt/cisco/wccai/byova-ai-simulator/src
RUN /opt/cisco/wccai/byova-ai-simulator/venv/bin/python -m grpc_tools.protoc -I./proto --python_out=./proto --grpc_python_out=./proto ./proto/*.proto


WORKDIR /opt/cisco/wccai/byova-ai-simulator/src/server

EXPOSE 8086

CMD ["/bin/sh", "-c", "/opt/cisco/wccai/byova-ai-simulator/venv/bin/python -u AIAgentServer.py"]